import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { posts } from '../content/posts.mjs';
import { projects } from '../content/projects.mjs';
const site = 'https://ghaith-amdouni.github.io';
const assetVersion = createHash('sha256')
  .update(await readFile('static/css/site.css'))
  .update(await readFile('static/css/akatsuki.css'))
  .update(await readFile('static/js/site.js'))
  .digest('hex').slice(0, 12);
const esc = s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const decode = s => s.replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n)).replaceAll('&amp;', '&').replaceAll('&quot;', '"');
const challenges = [];
async function walk(dir) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const file = `${dir}/${e.name}`;
    if (e.isDirectory()) await walk(file);
    else if (e.name === 'index.html') {
      const html = await readFile(file, 'utf8');
      const title = decode(html.match(/<title>(.*?)\s*\/\/[^<]+<\/title>/)?.[1] || file.split('/').at(-2));
      const collection = file.includes('mojo-jojo') ? 'MOJO-JOJO' : 'FST Bootcamp';
      challenges.push({ title, url: '/' + file, category: 'Pwn', collection, description: `${collection} · Authored challenge by r3t0x`, difficulty: Math.min(5, (html.split('<!-- Description -->')[0].match(/diff-dot filled/g) || []).length) });
    }
  }
}
await walk('challenge');
challenges.sort((a,b) => a.collection.localeCompare(b.collection) || a.title.localeCompare(b.title));
const cloud = `<svg class="akatsuki-cloud" viewBox="0 0 160 100" aria-hidden="true"><path d="M34 78C9 80 6 52 28 47C20 24 47 13 63 28C75 3 112 12 113 37C138 27 158 51 143 69C135 79 119 80 108 76C104 91 81 91 73 79C62 89 42 91 34 78Z"/><path class="cloud-whorl" d="M28 47C52 41 68 52 62 65C57 76 39 72 41 62M113 37C93 36 85 47 90 59"/></svg>`;
const icon = `<img class="brand-eye" src="/static/img/mangekyou.png" alt="" width="32" height="32">`;
const arrow = '<span aria-hidden="true">↗</span>';
function shell(title, description, body, {url='/', active='home', type='website'}={}) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0b0e"><title>${esc(title)} — r3t0x</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site}${url}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)} — r3t0x"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site}${url}"><meta property="og:image" content="${site}/static/img/social-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/static/img/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="r3t0x journal" href="/feed.xml"><link rel="stylesheet" href="/static/css/site.css?v=${assetVersion}"><link rel="stylesheet" href="/static/css/akatsuki.css?v=${assetVersion}"><script src="/static/js/site.js?v=${assetVersion}" defer></script></head><body>
  <a class="skip" href="#main">Skip to content</a><div class="reading-progress" aria-hidden="true"></div>
  <div class="systembar"><div><span class="arch-mini" aria-hidden="true">Λ</span> archlinux <span class="bar-sep">/</span> r3t0x@portfolio <span class="system-workspaces" aria-hidden="true"><b>01</b> 02 03</span></div><div><span class="online-dot"></span> ALL SYSTEMS NOMINAL <span class="bar-sep">/</span> <time id="clock">UTC</time></div></div>
  <header class="site-header"><a class="brand" href="/" aria-label="r3t0x home">${icon}<span>r3t0x<span class="muted">@arch</span></span></a><nav aria-label="Main navigation"><a href="/" ${active==='home'?'aria-current="page"':''}>~/home</a><a href="/blog/" ${active==='blog'?'aria-current="page"':''}>~/archive</a><a href="/projects/" ${active==='projects'?'aria-current="page"':''}>~/projects</a><a href="/static/docs/Ghaith-Amdouni-CV-English.pdf" download>CV ↓</a></nav><button class="search-trigger" data-open-search aria-label="Search site"><span>⌕</span><kbd>Ctrl K</kbd></button></header>
  <div class="archive-transition" id="archive-transition" aria-hidden="true"><div class="route-eyelid route-eyelid-top"></div><div class="route-eyelid route-eyelid-bottom"></div><div class="vault-coordinates"><span>00:00:01</span><span>ROUTE // LOCKED</span><span>0x00401337</span></div><div class="vault-eye"><span class="vault-symbol"></span><span class="vault-reticle"></span><i></i><i></i><i></i></div><div class="vault-caption"><span class="vault-kana">暁</span><p><small>TSUKUYOMI ROUTE SHIFT</small><b id="transition-label">ENTERING THE MEMORY VAULT</b><span id="transition-address">~/archive</span></p></div></div>
  <div class="ambient-clouds" aria-hidden="true">${cloud}${cloud}</div><div class="scroll-address" aria-hidden="true">RIP <span id="scroll-address">0x00000000</span></div><main id="main">${body}</main>
  <footer class="site-footer"><div class="footer-top"><a class="brand" href="/">${icon}<span>r3t0x<span class="muted">@arch</span></span></a><p>Always curious. Always one layer deeper.</p><a href="#main" class="text-link">Back to top ↑</a></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} Ghaith Amdouni <span class="red">·</span> Made with curiosity & caffeine.</span><div><a href="/projects/">Projects ↗</a><a href="https://github.com/Ghaith-amdouni">GitHub ↗</a><a href="https://www.linkedin.com/in/amdouni-ghaith">LinkedIn ↗</a><a href="/static/docs/Ghaith-Amdouni-CV-English.pdf" download>Résumé ↗</a><a href="/feed.xml">RSS ↗</a><button id="motion-toggle" aria-pressed="false">Motion: on</button></div></div></footer>
  <dialog id="search-dialog" class="search-vault" aria-labelledby="search-title"><div class="search-vault-mark" aria-hidden="true"><span></span><small>眼 // TRACE</small></div><div class="dialog-top"><div><span class="dialog-address">0xSEARCH_INDEX</span><h2 id="search-title">Trace a memory.</h2></div><button data-close-dialog aria-label="Close search">ESC</button></div><label for="site-search" class="search-command"><span aria-hidden="true">❯</span><span class="sr-only">Search challenges, projects, and pages</span><input id="site-search" type="search" placeholder="type a challenge, project, primitive…" autocomplete="off" spellcheck="false"></label><div class="search-scopes" role="group" aria-label="Search scope"><button type="button" data-search-scope="All" aria-pressed="true">ALL MEMORY</button><button type="button" data-search-scope="Challenge" aria-pressed="false">CHALLENGES</button><button type="button" data-search-scope="Project" aria-pressed="false">PROJECTS</button></div><div class="search-readout"><span><i></i> INDEX ONLINE</span><b id="search-count">0 addresses</b></div><div id="search-results" aria-live="polite"></div><div class="dialog-bottom"><span>↑↓ TRACE</span><span>ENTER OPEN</span><span>ESC DISMISS</span></div></dialog>
  <div class="toast" id="toast" role="status"></div></body></html>`;
}
function art(post) {
  if(post.art==='pipeline') return `<div class="post-art pipeline-art" aria-hidden="true"><span>git push</span><i>→</i><span>build</span><i>→</i><span class="art-active">deploy <b>✓</b></span><small>STATUS: ALL CHECKS PASSED</small></div>`;
  if(post.art==='network') return `<div class="post-art network-art" aria-hidden="true"><span>◉</span><i>······</i><span>◈</span><i>······</i><span>◉</span><small>source → relay → destination</small></div>`;
  return `<div class="post-art hello-art" aria-hidden="true"><span class="ghost-code">48 65 6c 6c 6f 20 77 6f 72 6c 64</span><strong><span>./</span>hello_world<span class="cursor">_</span></strong><small>PROCESS STARTED. CURIOSITY LOADED.</small></div>`;
}
const postUrl = post => post.slug === 'taskmanager' ? '/projects/#taskpilot-devops' : post.slug === 'network-simulations' ? '/projects/#omnetpp-mesh-5g' : '/#about';
function postCard(post) { return `<a class="post-card" href="${postUrl(post)}">${art(post)}<div class="post-card-body"><div class="post-meta"><span class="tag">${post.category}</span><span>${new Date(post.date).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'})} · project note</span></div><h3>${post.title} ${arrow}</h3><p>${post.description}</p></div></a>`; }
const heading=(n,title,sub,link='')=>`<div class="section-heading"><div><p class="eyebrow">${n} <span>/</span> ${sub}</p><h2>${title}</h2></div>${link}</div>`;
const awards = [ ['01','SecuriNets ISI','National finals'], ['01','SecuriNets ISI','Qualifications'], ['01','Friendly CTF ENIT','Competition'], ['04','SecuriNets International','Qualifications · Africa'], ['07','SecuriNets International','International finals'], ['08','Claw The Flag','Top 8 finish'] ];
const homeProjects = projects.filter(project => project.featured);
const home = `<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="online-dot"></span> AKATSUKI SPIRIT. DEBUGGER MIND.</p><h1><span class="hero-prefix">./</span>r3t0x<span class="cursor">_</span></h1><h2>Ghaith Amdouni<span class="red">.</span></h2><p class="hero-role">Binary exploitation <span>×</span> Systems <span>×</span> Curiosity</p><p class="hero-description">I pull things apart to understand how they work.<br>SecuriNets Technical Team Instructor, CTF player, and Networks & Telecommunications student at INSAT.</p><div class="hero-actions"><a class="button primary" href="/blog/">Explore the archive <span>↗</span></a><a class="button" href="/static/docs/Ghaith-Amdouni-CV-English.pdf" download>English CV <span>↓</span></a></div><div class="hero-links"><a href="https://github.com/Ghaith-amdouni">GitHub ↗</a><a href="https://www.linkedin.com/in/amdouni-ghaith">LinkedIn ↗</a><a href="mailto:ghaith.amdouni@insat.ucar.tn">Email ↗</a><span><span class="online-dot"></span> Tunis, Tunisia</span></div></div>
  <div class="hero-visual"><img class="hero-sharingan" src="/static/img/mangekyou.png" width="290" height="290" alt="" aria-hidden="true"><div class="orbit orbit-one" aria-hidden="true"></div><div class="orbit orbit-two" aria-hidden="true"></div><span class="visual-addr" aria-hidden="true">0x00401337 · rwx</span><div class="portrait-window"><div class="window-title"><span class="window-dots"><i></i><i></i><i></i></span><span>~/r3t0x/whoami</span><span class="red">暁</span></div><div class="portrait-image"><img src="/static/img/ghaith.webp" alt="Ghaith Amdouni working on his laptop at a technology event" width="800" height="1200" fetchpriority="high"><div class="portrait-caption"><span><i class="online-dot"></i> GHAITH AMDOUNI</span><span>aka. r3t0x</span></div></div><div class="portrait-bottom"><span><b>OS</b> Arch Linux</span><span><b>FOCUS</b> Pwn & systems</span></div></div><div class="floating-tag"><span class="red">❯</span> curiosity <span class="muted">--always</span><span class="cursor">▌</span></div></div></section>
  <div class="specialties"><div class="wrap"><span><i>01</i> BINARY EXPLOITATION</span><b>✳</b><span><i>02</i> REVERSE ENGINEERING</span><b>✳</b><span><i>03</i> NETWORKS & SYSTEMS</span><b>✳</b><span><i>04</i> ARCH LINUX</span></div></div>
  <section class="section wrap" id="journal">${heading('01','The latest bytes.','THE JOURNAL',`<a class="text-link" href="/blog/">View the archive ${arrow}</a>`)}<div class="posts-grid">${posts.map(postCard).join('')}</div><a class="archive-callout" href="/blog/?category=Pwn"><div><span class="red">❯</span> <strong>Looking for CTF challenges?</strong><span class="muted"> ${challenges.length} authored challenges across MOJO-JOJO & FST Bootcamp.</span></div><span>Open archive ↗</span></a></section>
  <section class="section wrap" id="about">${heading('02','More than a handle.','WHOAMI')}<div class="about-grid"><div class="about-copy"><p class="large-copy">Somewhere between a packet trace and a debugger, <span>I feel at home.</span></p><p>I'm a SecuriNets Technical Team Instructor and a Networks & Telecommunications student at <a href="https://insat.rnu.tn/">INSAT</a>, based in Tunis. My work connects cybersecurity, Linux, networking, and software development.</p><p>I build challenges, compete in CTFs, and explore the layers underneath the interface. From network simulations to cloud-native applications, I like understanding the whole system.</p><div class="skill-tags"><span>Binary exploitation</span><span>C / C++</span><span>Python</span><span>Linux</span><span>Docker</span><span>Kubernetes</span><span>Networking</span><span>DevSecOps</span></div><a class="text-link" href="/static/docs/Ghaith-Amdouni-CV-English.pdf" download>Download my English CV ↓</a></div>
  <div class="terminal"><div class="window-title"><span class="window-dots"><i></i><i></i><i></i></span><span>r3t0x@arch: ~</span><span>zsh</span></div><div class="terminal-content"><div class="terminal-fetch"><pre class="arch-ascii" aria-hidden="true">       /\\
      /  \\
     /\\   \\
    /      \\
   /   ,,   \\
  /   |  |   \\
 /_-''    ''-_\\</pre><div><strong>r3t0x<span class="muted">@</span>arch</strong><span class="muted">──────────────────</span><span><b>name</b> Ghaith Amdouni</span><span><b>location</b> Tunis, TN</span><span><b>education</b> INSAT</span><span><b>interests</b> pwn, systems</span><span class="terminal-swatches" aria-hidden="true">▅▅▅▅▅▅</span></div></div><div id="terminal-output" class="terminal-output" role="log" aria-live="polite"><p class="muted">Welcome to my corner of the internet.<br>Type <span class="red">help</span> to look around.</p></div><form id="terminal-form"><label for="terminal-input"><span class="red">r3t0x</span><span class="muted">@arch</span> <span class="green">❯</span></label><input id="terminal-input" aria-label="Terminal command" placeholder="help" autocomplete="off" spellcheck="false" maxlength="120"></form></div></div></div></section>
  <section class="section wrap" id="achievements">${heading('03','Capture flags. Leave a mark.','CTF ACHIEVEMENTS')}<div class="awards-grid">${awards.map(([rank,name,detail])=>`<div class="award"><div class="award-rank ${rank==='01'?'gold':''}"><span>#</span>${rank}</div><div><h3>${name}</h3><p>${detail}</p></div><span class="award-star" aria-hidden="true">✧</span></div>`).join('')}</div></section>
  <section class="section wrap" id="projects">${heading('04','Built from curiosity.','SELECTED PROJECTS',`<a class="text-link" href="/projects/">View every project ${arrow}</a>`)}<div class="projects-grid">${homeProjects.map((project,index)=>`<article class="project-card"><div class="project-top"><span>${String(index+1).padStart(2,'0')} / PROJECT</span><span aria-hidden="true">${project.icon}</span></div><p class="eyebrow">${project.kicker}</p><h3>${project.title}</h3><p>${project.description}</p><div class="project-tech">${project.stack.join(' / ')}</div><a class="text-link" href="/projects/#${project.slug}">Read project notes ↗</a></article>`).join('')}</div></section>
  <section class="section wrap" id="experience">${heading('05','The journey so far.','EXPERIENCE & LEARNING')}<div class="experience-grid"><div><article class="timeline-item"><span class="timeline-dot"></span><p class="eyebrow">CURRENT ROLE</p><h3>Technical Team Instructor</h3><p class="company">SecuriNets</p><p>Teach technical workshops and guide learners through practical cybersecurity and binary-exploitation material.</p></article><article class="timeline-item"><span class="timeline-dot"></span><p class="eyebrow">01 — 31 AUG 2026</p><h3>Digital Forensics Police Internship</h3><p class="company">FACEIS · AI & Security Engineering</p><p>Designed and built a facial investigation platform combining RetinaFace detection, ArcFace embeddings, FAISS similarity search, role-based access, and audited investigation workflows.</p><a class="text-link" href="/projects/#faceis">Read the FACEIS case notes ↗</a></article><article class="timeline-item"><span class="timeline-dot"></span><p class="eyebrow">JUN — AUG 2024</p><h3>Web Development Intern / Collaborator</h3><p class="company">Zedka Services</p><p>Contributed to development and maintenance of the MSJVerre website, working across the front end and back end, page optimization, content integration, and technical configuration.</p></article><article class="timeline-item"><span class="timeline-dot"></span><p class="eyebrow">EDUCATION</p><h3>Networks & Telecommunications</h3><p class="company">INSAT · Tunis</p><p>Student at the National Institute of Applied Science and Technology, with interests spanning cybersecurity, networking, and software development.</p></article></div><div class="certifications"><p class="eyebrow">CONTINUOUS LEARNING</p><h3>Credentials, collected.</h3><ul><li><span>CCNA: Introduction to Networks</span><small>Cisco</small></li><li><span>CCNA: Switching, Routing & Wireless Essentials</span><small>Cisco</small></li><li><span>Google Cybersecurity</span><small>Coursera</small></li><li><span>CS50's Introduction to Computer Science</span><small>Harvard</small></li><li><span>Certified Red Team Operations Management</span></li></ul><a class="text-link" href="https://www.credly.com/users/ghaith-amdouni">View Credly profile ↗</a></div></div></section>
  <section class="contact-section wrap" id="contact"><div><p class="eyebrow"><span class="online-dot"></span> LET'S CONNECT</p><h2>Have something<br>interesting in mind<span class="red">?</span></h2><p>Projects, CTFs, systems, or a good conversation. My inbox is open.</p></div><div class="contact-actions"><a class="button primary" href="mailto:ghaith.amdouni@insat.ucar.tn">Say hello ↗</a><button class="button" data-copy-email>Copy email ⧉</button><a class="text-link" href="/static/docs/Ghaith-Amdouni-CV-English.pdf" download>Download English CV ↓</a></div></section>
  <section class="wrap visitor-telemetry" aria-label="Site visits"><div class="telemetry-copy"><p class="eyebrow"><span class="online-dot"></span> VISITOR TELEMETRY</p><code><b>$</b> tail -f /var/log/visitor.signals</code><div class="visit-seal"><span class="visit-kana" aria-hidden="true">暁</span><div><small>OUTSIDER SIGNAL COUNT</small><img src="https://hits.sh/ghaith-amdouni.github.io.svg?view=total&amp;style=flat-square&amp;label=visits&amp;color=f04450&amp;labelColor=111116" alt="Live visit count" width="96" height="20"></div><i aria-hidden="true"></i></div></div><div class="telemetry-radar" aria-hidden="true"><div class="radar-eye"><img src="/static/img/mangekyou.png" alt="" width="110" height="110"><i></i><i></i><i></i></div><div class="packet-log"><span>GET / HTTP/2</span><b>200 OK</b><span>source&nbsp; anonymous</span><span>cookies&nbsp; 0</span></div></div><p class="telemetry-privacy"><b>ZERO-COOKIE CHANNEL</b><span>No identity. No tracking. Just a pulse from the outside world.</span></p></section>`;
await writeFile('index.html',shell('Ghaith Amdouni · Binary exploitation & systems','The personal blog and portfolio of Ghaith Amdouni (r3t0x). CTF challenges, Linux, networking, and projects.',home));
// Keep old résumé bookmarks working; the full portfolio now lives on the home page.
await mkdir('resume', {recursive:true});
await writeFile('resume/index.html', `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url=/#experience"><link rel="canonical" href="${site}/"><title>Experience · Ghaith Amdouni</title></head><body><p>The résumé is now part of the <a href="/#experience">main portfolio</a>. <a href="/static/docs/Ghaith-Amdouni-CV-English.pdf" download>Download the English CV</a>.</p></body></html>`);

function projectCase(project, index) {
  return `<details id="${project.slug}" class="project-case" data-title="${esc(project.title)}" data-search="${esc(`${project.description} ${project.kicker} ${project.stack.join(' ')}`)}">
    <summary><div class="project-case-art" aria-hidden="true"><span>${project.icon}</span><small>0x${(0x5000 + index * 0x100).toString(16).padStart(8,'0')}</small>${cloud}</div><div class="project-case-copy"><div class="entry-meta"><span class="tag">${project.kicker}</span><span>PUBLIC REPOSITORY</span></div><h2>${project.title}</h2><p>${project.description}</p><div class="project-stack">${project.stack.map(item=>`<span>${item}</span>`).join('')}</div><div class="note-toggle"><span>Open case notes</span><span aria-hidden="true">＋</span></div></div></summary>
    <div class="prose project-note-body">${project.body}<div class="project-note-actions"><a class="button primary" href="${project.repo}">View source on GitHub ↗</a><button class="button" data-close-project>Close notes ↑</button></div></div>
  </details>`;
}
const projectsBody = `<div class="wrap projects-page"><a class="text-link" href="/">← Back to home</a><div class="projects-hero"><div><p class="eyebrow">~/PROJECTS <span>/</span> BUILT SYSTEMS</p><h1>Ideas that<br>made it to code<span class="red">.</span></h1><p>Security research, exploit development, infrastructure, networks, and embedded systems—selected from my public GitHub work.</p></div><div class="project-orbit" aria-hidden="true"><img src="/static/img/mangekyou.png" alt="" width="260" height="260"><code>git log --author=r3t0x</code></div></div><div class="projects-intro"><p>Each card opens its notes here, keeping the site focused while still showing the engineering behind the repository.</p><a class="text-link" href="https://github.com/Ghaith-amdouni?tab=repositories">All repositories on GitHub ↗</a></div><form class="project-trace" id="project-form" role="search"><label><span class="trace-prompt" aria-hidden="true">❯</span><span class="sr-only">Search projects</span><input type="search" id="project-search" placeholder="trace by project, stack, or system…" autocomplete="off" spellcheck="false"></label><div class="trace-status"><span><i></i> REPOSITORY INDEX</span><b id="project-result-count">${projects.length} case files</b><button type="button" id="reset-project-search" hidden>CLEAR ×</button></div></form><div class="project-case-grid" id="project-results">${projects.map(projectCase).join('')}</div><div id="project-empty" class="project-empty" hidden><span>失</span><h2>No project signature found.</h2><p>Try a stack such as Python, Kubernetes, C, or IoT.</p><button class="button" id="reset-project-empty">Reset trace ↺</button></div></div>`;
await mkdir('projects',{recursive:true});
await writeFile('projects/index.html',shell('Projects','Selected security, systems, DevOps, networking, and embedded projects by Ghaith Amdouni.',projectsBody,{url:'/projects/',active:'projects'}));

function challengeCard(c, i) {
  const address = '0x' + (0x401000 + i * 0x100).toString(16).padStart(8, '0');
  const level = ['','Entry','Getting started','Intermediate','Advanced','Expert'][c.difficulty] || 'Challenge';
  return `<article class="archive-entry challenge-card" data-title="${esc(c.title)}" data-category="Pwn" data-collection="${c.collection}" data-search="${esc(c.description)}">
    <a href="${c.url}" aria-labelledby="challenge-title-${i}">
      <div class="challenge-card-art" aria-hidden="true"><span class="card-address">${address}</span><span class="hex-watermark">48 89 e5<br>31 c0 c3</span>${cloud}<span class="card-collection">${c.collection === 'MOJO-JOJO' ? 'MOJO // ' : 'FST // '}${String(i+1).padStart(2,'0')}</span></div>
      <div class="challenge-card-content"><div class="entry-meta"><span class="tag pwn">Pwn</span><span>${c.collection}</span></div>
      <h2 id="challenge-title-${i}">${esc(c.title)}<span class="function-suffix">()</span></h2>
      <p>${esc(c.description)}</p>
      <div class="card-difficulty"><span>${level}</span><span class="difficulty-blocks" aria-label="Difficulty ${c.difficulty} of 5">${Array.from({length:5},(_,n)=>`<i class="${n<c.difficulty?'filled':''}"></i>`).join('')}</span></div>
      <div class="challenge-card-footer"><span>Read challenge</span><span class="red" aria-hidden="true">↗</span></div></div>
    </a>
  </article>`;
}
const archiveBody = `<div class="wrap archive-page">
  <a class="text-link" href="/">← Back to home</a>
  <div class="archive-hero"><div><p class="eyebrow">~/ARCHIVE <span>/</span> THE MEMORY VAULT</p><h1>Every byte.<br>A new story<span class="red">.</span></h1><div class="archive-manifest" aria-label="Archive themes"><span><b>MOJO</b> stack · heap · linker</span><span><b>FST</b> ROP · shellcode · format strings</span><span><b>MODE</b> read · reason · exploit</span></div></div><div class="archive-sigil" aria-hidden="true"><img src="/static/img/mangekyou.png" alt="" width="290" height="290"><span>暁 / MEMORY VAULT</span></div></div>
  <form class="archive-toolbar" id="archive-form" role="search"><label class="archive-search"><span aria-hidden="true">❯</span><span class="sr-only">Search the archive</span><input type="search" id="archive-search" name="q" placeholder="trace a challenge, primitive, or collection…" autocomplete="off" spellcheck="false"></label><label class="sort-control"><span>SORT //</span><select id="archive-sort" name="sort"><option value="default">Memory order</option><option value="az">Title: A–Z</option><option value="za">Title: Z–A</option></select></label></form>
  <div class="archive-filters" aria-label="Filter category">${['All','Pwn'].map((c,i)=>`<button data-category="${c}" aria-pressed="${i===0}">${c}<span>${challenges.length}</span></button>`).join('')}</div>
  <div class="archive-subbar"><label>Collection <select id="collection-filter"><option value="All">All collections</option><option>MOJO-JOJO</option><option>FST Bootcamp</option></select></label><span id="result-count" role="status">${challenges.length} challenges</span></div>
  <div id="archive-results" class="archive-card-grid">${challenges.map(challengeCard).join('')}</div>
  <div id="archive-empty" hidden><span class="red">0x00000000</span><h2>No matching bytes.</h2><p>Try another search or reset the filters.</p><button class="button" id="reset-filters">Reset filters ↺</button></div>
</div>`;
await mkdir('blog',{recursive:true});
await writeFile('blog/index.html',shell('The challenge archive','Explore Ghaith Amdouni’s MOJO-JOJO and FST binary-exploitation challenge cards.',archiveBody,{url:'/blog/',active:'blog'}));
// Older note URLs stay compatible after project notes move to ~/projects.
for (const p of posts) {
  const target = postUrl(p);
  await mkdir(`blog/${p.slug}`, {recursive:true});
  await writeFile(`blog/${p.slug}/index.html`, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url=${target}"><link rel="canonical" href="${site}${target}"><title>${esc(p.title)}</title></head><body><a href="${target}">Continue to ${esc(p.title)}</a></body></html>`);
}
await writeFile('404.html',shell('404 · Address not mapped','This address is not mapped. Return to the r3t0x archive.',`<section class="wrap error-page"><p class="eyebrow">SEGMENT NOT FOUND</p><h1>0x<span class="red">404</span></h1><h2>This address isn't mapped.</h2><p>The page may have moved. Let's get you back to a known location.</p><div class="hero-actions"><a class="button primary" href="/">Return home ↗</a><a class="button" href="/blog/">Browse the archive</a></div></section>`,{url:'/404.html'}));
const pages=[{title:'Home',url:'/',category:'Page',description:'Ghaith Amdouni · r3t0x'},{title:'About Ghaith',url:'/#about',category:'Page',description:'Biography and interactive terminal'},{title:'Projects',url:'/projects/',category:'Page',description:'Security, systems, DevOps, networking, and embedded project notes'},{title:'SecuriNets · Experience',url:'/#experience',category:'Page',description:'Technical Team Instructor · experience and certifications'},{title:'English CV · Download',url:'/static/docs/Ghaith-Amdouni-CV-English.pdf',category:'PDF',description:'Ghaith Amdouni’s English résumé'},{title:'Challenge archive',url:'/blog/',category:'Page',description:'Browse MOJO-JOJO and FST binary-exploitation challenges'},...projects.map(project=>({title:project.title,url:`/projects/#${project.slug}`,category:'Project',description:project.description})),...posts.map(p=>({...p,body:undefined,url:postUrl(p)})),...challenges];
await mkdir('static/data',{recursive:true}); await writeFile('static/data/search.json',JSON.stringify(pages));
await writeFile('feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>r3t0x · Ghaith Amdouni</title><link>${site}</link><description>Notes on systems, networking, and projects.</description><language>en</language><atom:link href="${site}/feed.xml" rel="self" type="application/rss+xml"/>${posts.map(p=>`<item><title>${esc(p.title)}</title><link>${site}${postUrl(p)}</link><guid>${site}${postUrl(p)}</guid><pubDate>${new Date(p.date).toUTCString()}</pubDate><description>${esc(p.description)}</description></item>`).join('')}</channel></rss>`);
await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/blog/','/projects/',...challenges.map(c=>c.url)].map(u=>`<url><loc>${site}${esc(u)}</loc></url>`).join('')}</urlset>`);
await writeFile('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site}/sitemap.xml\n`);
console.log(`Built Home, ${challenges.length}-card Challenge Archive, and ${projects.length}-case Projects page, plus compatibility redirects, search, RSS, and sitemap.`);
